### PR TITLE
Add tox to lint and run tests in Python 2 and 3

### PR DESCRIPTION
**Pull request by Scotchester**
Also includes:
- A lot of updates to resolve flake8 and isort warnings and errors
- New tests for the xml_payloads module
- Fixes for bugs discovered when writing those new tests

## Testing

1. Pull branch
2. `tox`

### CODE REVIEW

**Review by cwdavies — COMMENTED** [review]
I get an ERROR running tox on the toxify branch of govdelivery.
```script
$ git remote -v
origin	https://github.com/cfpb/govdelivery.git (fetch)
origin	https://github.com/cfpb/govdelivery.git (push)
$ git branch -l
  master
* toxify
$ tox
/Users/DaviesC/homebrew/Cellar/tox/3.13.2/libexec/lib/python3.7/site-packages/packaging/requirements.py:57: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'specifier' on And expression collides with '_original_end' on contained expression
  VERSION_SPEC = originalTextFor(_VERSION_SPEC)("specifier")
/Users/DaviesC/homebrew/Cellar/tox/3.13.2/libexec/lib/python3.7/site-packages/packaging/requirements.py:60: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'marker' on And expression collides with '_original_end' on contained expression
  MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
GLOB sdist-make: /Users/DaviesC/Projects/CFPB/govdelivery/setup.py
lint create: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/lint
lint installdeps: flake8>=2.2.0, isort>=4.2.15
lint inst: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/.tmp/package/1/govdelivery-1.2.zip
lint installed: certifi==2019.9.11,chardet==3.0.4,coverage==4.5.4,entrypoints==0.3,flake8==3.7.9,govdelivery==1.2,idna==2.8,isort==4.3.21,mccabe==0.6.1,mock==2.0.0,pbr==5.4.3,pycodestyle==2.5.0,pyflakes==2.1.1,requests==2.22.0,responses==0.10.6,six==1.13.0,urllib3==1.25.7
lint run-test-pre: PYTHONHASHSEED='3492074235'
lint run-test: commands[0] | flake8 govdelivery
lint run-test: commands[1] | isort --check-only --diff --recursive govdelivery
ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:before2019-11-19 16:20:56.031334
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:after	2019-11-19 16:21:28.406380
@@ -1,7 +1,8 @@
 import re
-import six
 import warnings
 from string import Template
+
+import six


 def format_phone(phone):
ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/api.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/api.py:before	2019-11-19 16:20:56.030391
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/api.py:after	2019-11-19 16:21:28.412924
@@ -1,11 +1,11 @@
 import base64
 import os
+from string import Template
+
+import requests
 import six
-from string import Template
-
-import requests
+
 from govdelivery import xml_payloads, xml_response_parsers
-

 if six.PY2:
     import urlparse  # pragma: no cover
ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/test_xml_response_parsers.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/test_xml_response_parsers.py:before	2019-11-19 16:20:56.031126
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/test_xml_response_parsers.py:after	2019-11-19 16:21:28.419187
@@ -3,8 +3,7 @@
 from govdelivery.tests.utils import load_data
 from govdelivery.xml_response_parsers import (
     listed_topic_xml_as_dict, subscriber_responses_as_list_of_dicts,
-    subscriber_topics_as_list, topic_xml_as_dict
-)
+    subscriber_topics_as_list, topic_xml_as_dict)


 class TestTopicListingParsers(unittest.TestCase):
ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/utils.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/utils.py:before	2019-11-19 16:20:35.292178
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/utils.py:after	2019-11-19 16:21:28.423348
@@ -1,6 +1,5 @@
 import codecs
 from os import path
-

 testdata_dir = path.join(path.dirname(__file__), 'test_api_responses')

ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/test_api.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/test_api.py:before	2019-11-19 16:20:56.030783
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/test_api.py:after2019-11-19 16:21:28.429027
@@ -2,13 +2,13 @@
 import unittest

 import responses
-from govdelivery.api import (
-    GovDelivery, authenticated_session, get_full_url_to_call
-)
+from mock import patch
+from requests.models import Response
+
+from govdelivery.api import (GovDelivery, authenticated_session,
+                             get_full_url_to_call)
 from govdelivery.tests.utils import load_data
 from govdelivery.xml_response_parsers import topic_xml_as_dict
-from mock import patch
-from requests.models import Response


 class TestClientUtilities(unittest.TestCase):
ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/test_xml_payloads.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/test_xml_payloads.py:before	2019-11-19 16:20:56.030925
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/test_xml_payloads.py:after	2019-11-19 16:21:28.435573
@@ -1,9 +1,8 @@
 import unittest

-from govdelivery.xml_payloads import (
-    create_subscriber, format_phone, set_subscriber_categories,
-    set_subscriber_topics
-)
+from govdelivery.xml_payloads import (create_subscriber, format_phone,
+                                      set_subscriber_categories,
+                                      set_subscriber_topics)


 class TestXMLPayloadUtils(unittest.TestCase):
ERROR: InvocationError for command /Users/DaviesC/Projects/CFPB/govdelivery/.tox/lint/bin/isort --check-only --diff --recursive govdelivery (exited with code 1)
py27 create: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/py27
py27 inst: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/.tmp/package/1/govdelivery-1.2.zip
py27 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,certifi==2019.9.11,chardet==3.0.4,cookies==2.2.1,coverage==4.5.4,funcsigs==1.0.2,govdelivery==1.2,idna==2.8,mock==2.0.0,pbr==5.4.3,requests==2.22.0,responses==0.10.6,six==1.13.0,urllib3==1.25.7
py27 run-test-pre: PYTHONHASHSEED='3492074235'
py27 run-test: commands[0] | coverage erase
py27 run-test: commands[1] | coverage run --source=govdelivery -m unittest discover
................./Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:15: DeprecationWarning: The phone number formatter will be deprecated in a future release of govdelivery. Going forward, please ensure that your application passes phone numbers in the format that the GovDelivery API requires (a ten-digit string with no punctuation).
  DeprecationWarning
......
----------------------------------------------------------------------
Ran 23 tests in 0.044s

OK
py27 run-test: commands[2] | coverage report -m
Name                                             Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------
govdelivery/__init__.py                              1      0   100%
govdelivery/api.py                                  79     26    67%   58, 100-110, 130-137, 141-152, 168-179, 183-199, 207-228
govdelivery/tests/__init__.py                        0      0   100%
govdelivery/tests/test_api.py                       58      0   100%
govdelivery/tests/test_test_utils.py                 5      0   100%
govdelivery/tests/test_xml_payloads.py              39      0   100%
govdelivery/tests/test_xml_response_parsers.py      24      0   100%
govdelivery/tests/utils.py                           7      0   100%
govdelivery/xml_payloads.py                         47      6    87%   106-116, 120-129
govdelivery/xml_response_parsers.py                 31      0   100%
------------------------------------------------------------------------------
TOTAL                                              291     32    89%
py36 create: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/py36
py36 inst: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/.tmp/package/1/govdelivery-1.2.zip
py36 installed: certifi==2019.9.11,chardet==3.0.4,coverage==4.5.4,govdelivery==1.2,idna==2.8,mock==2.0.0,pbr==5.4.3,requests==2.22.0,responses==0.10.6,six==1.13.0,urllib3==1.25.7
py36 run-test-pre: PYTHONHASHSEED='3492074235'
py36 run-test: commands[0] | coverage erase
py36 run-test: commands[1] | coverage run --source=govdelivery -m unittest discover
............./Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:15: DeprecationWarning: The phone number formatter will be deprecated in a future release of govdelivery. Going forward, please ensure that your application passes phone numbers in the format that the GovDelivery API requires (a ten-digit string with no punctuation).
  DeprecationWarning
..........
----------------------------------------------------------------------
Ran 23 tests in 0.012s

OK
py36 run-test: commands[2] | coverage report -m
Name                                             Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------
govdelivery/__init__.py                              1      0   100%
govdelivery/api.py                                  79     26    67%   58, 100-110, 130-137, 141-152, 168-179, 183-199, 207-228
govdelivery/tests/__init__.py                        0      0   100%
govdelivery/tests/test_api.py                       58      0   100%
govdelivery/tests/test_test_utils.py                 5      0   100%
govdelivery/tests/test_xml_payloads.py              39      0   100%
govdelivery/tests/test_xml_response_parsers.py      24      0   100%
govdelivery/tests/utils.py                           7      0   100%
govdelivery/xml_payloads.py                         47      6    87%   106-116, 120-129
govdelivery/xml_response_parsers.py                 31      0   100%
------------------------------------------------------------------------------
TOTAL                                              291     32    89%
___________________________________ summary ____________________________________
ERROR:   lint: commands failed
  py27: commands succeeded
  py36: commands succeeded
```

**Comment by Scotchester** [comment]
@cwdavies Interesting! Thanks for the report. Seems that the failure is in linting the import sorting. When I run this locally, it all works fine. Maybe @willbarton knows what might cause this? I wonder if it's some Python version thing. I was running from a Python 2.7 local environment, but I see you're running from 3.7. Not sure how or if this would affect isort within tox. I can't tell for sure what version of Python isort is running with.

**Comment by Scotchester** [comment]
@cwdavies I've pushed a fix. Please re-test.

Thanks to @willbarton for the nudge in the right direction.

**Comment by cwdavies** [comment]
```$ tox
GLOB sdist-make: /Users/DaviesC/Projects/CFPB/govdelivery/setup.py
lint create: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/lint
lint installdeps: flake8>=2.2.0, isort>=4.2.15
lint inst: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/.tmp/package/1/govdelivery-1.2.zip
lint installed: certifi==2019.9.11,chardet==3.0.4,coverage==4.5.4,entrypoints==0.3,flake8==3.7.9,govdelivery==1.2,idna==2.8,isort==4.3.21,mccabe==0.6.1,mock==2.0.0,pbr==5.4.3,pycodestyle==2.5.0,pyflakes==2.1.1,requests==2.22.0,responses==0.10.6,six==1.13.0,urllib3==1.25.7
lint run-test-pre: PYTHONHASHSEED='3114943055'
lint run-test: commands[0] | flake8 govdelivery
lint run-test: commands[1] | isort --check-only --diff --recursive govdelivery
ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:before	2019-11-21 12:08:12.322478
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:after	2019-11-21 12:09:53.023251
@@ -1,5 +1,6 @@
+import six
+
 import re
-import six
 import warnings
 from string import Template

ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/api.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/api.py:before	2019-11-21 12:08:12.321477
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/api.py:after	2019-11-21 12:09:53.030101
@@ -1,11 +1,11 @@
+import six
+
 import base64
 import os
-import six
 from string import Template

 import requests
 from govdelivery import xml_payloads, xml_response_parsers
-

 if six.PY2:
     import urlparse  # pragma: no cover
ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/utils.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/utils.py:before	2019-11-21 12:07:56.657335
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/utils.py:after	2019-11-21 12:09:53.041281
@@ -1,6 +1,5 @@
 import codecs
 from os import path
-

 testdata_dir = path.join(path.dirname(__file__), 'test_api_responses')

ERROR: InvocationError for command /Users/DaviesC/Projects/CFPB/govdelivery/.tox/lint/bin/isort --check-only --diff --recursive govdelivery (exited with code 1)
py27 create: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/py27
py27 inst: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/.tmp/package/1/govdelivery-1.2.zip
py27 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support,certifi==2019.9.11,chardet==3.0.4,cookies==2.2.1,coverage==4.5.4,funcsigs==1.0.2,govdelivery==1.2,idna==2.8,mock==2.0.0,pbr==5.4.3,requests==2.22.0,responses==0.10.6,six==1.13.0,urllib3==1.25.7
py27 run-test-pre: PYTHONHASHSEED='3114943055'
py27 run-test: commands[0] | coverage erase
py27 run-test: commands[1] | coverage run --source=govdelivery -m unittest discover
................./Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:15: DeprecationWarning: The phone number formatter will be deprecated in a future release of govdelivery. Going forward, please ensure that your application passes phone numbers in the format that the GovDelivery API requires (a ten-digit string with no punctuation).
  DeprecationWarning
......
----------------------------------------------------------------------
Ran 23 tests in 0.042s

OK
py27 run-test: commands[2] | coverage report -m
Name                                             Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------
govdelivery/__init__.py                              1      0   100%
govdelivery/api.py                                  79     26    67%   58, 100-110, 130-137, 141-152, 168-179, 183-199, 207-228
govdelivery/tests/__init__.py                        0      0   100%
govdelivery/tests/test_api.py                       58      0   100%
govdelivery/tests/test_test_utils.py                 5      0   100%
govdelivery/tests/test_xml_payloads.py              39      0   100%
govdelivery/tests/test_xml_response_parsers.py      24      0   100%
govdelivery/tests/utils.py                           7      0   100%
govdelivery/xml_payloads.py                         47      6    87%   106-116, 120-129
govdelivery/xml_response_parsers.py                 31      0   100%
------------------------------------------------------------------------------
TOTAL                                              291     32    89%
py36 create: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/py36
py36 inst: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/.tmp/package/1/govdelivery-1.2.zip
py36 installed: certifi==2019.9.11,chardet==3.0.4,coverage==4.5.4,govdelivery==1.2,idna==2.8,mock==2.0.0,pbr==5.4.3,requests==2.22.0,responses==0.10.6,six==1.13.0,urllib3==1.25.7
py36 run-test-pre: PYTHONHASHSEED='3114943055'
py36 run-test: commands[0] | coverage erase
py36 run-test: commands[1] | coverage run --source=govdelivery -m unittest discover
............./Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:15: DeprecationWarning: The phone number formatter will be deprecated in a future release of govdelivery. Going forward, please ensure that your application passes phone numbers in the format that the GovDelivery API requires (a ten-digit string with no punctuation).
  DeprecationWarning
..........
----------------------------------------------------------------------
Ran 23 tests in 0.012s

OK
py36 run-test: commands[2] | coverage report -m
Name                                             Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------
govdelivery/__init__.py                              1      0   100%
govdelivery/api.py                                  79     26    67%   58, 100-110, 130-137, 141-152, 168-179, 183-199, 207-228
govdelivery/tests/__init__.py                        0      0   100%
govdelivery/tests/test_api.py                       58      0   100%
govdelivery/tests/test_test_utils.py                 5      0   100%
govdelivery/tests/test_xml_payloads.py              39      0   100%
govdelivery/tests/test_xml_response_parsers.py      24      0   100%
govdelivery/tests/utils.py                           7      0   100%
govdelivery/xml_payloads.py                         47      6    87%   106-116, 120-129
govdelivery/xml_response_parsers.py                 31      0   100%
------------------------------------------------------------------------------
TOTAL                                              291     32    89%
_____________________________________________________ summary ______________________________________________________
ERROR:   lint: commands failed
  py27: commands succeeded
  py36: commands succeeded```

**Comment by cwdavies** [comment]
```
$ tox -e lint
GLOB sdist-make: /Users/DaviesC/Projects/CFPB/govdelivery/setup.py
lint inst-nodeps: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/.tmp/package/1/govdelivery-1.2.zip
lint installed: certifi==2019.9.11,chardet==3.0.4,coverage==4.5.4,entrypoints==0.3,flake8==3.7.9,govdelivery==1.2,idna==2.8,isort==4.3.21,mccabe==0.6.1,mock==2.0.0,pbr==5.4.3,pycodestyle==2.5.0,pyflakes==2.1.1,requests==2.22.0,responses==0.10.6,six==1.13.0,urllib3==1.25.7
lint run-test-pre: PYTHONHASHSEED='461902292'
lint run-test: commands[0] | flake8 govdelivery
lint run-test: commands[1] | isort --check-only --diff --recursive govdelivery
ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:before	2019-11-21 12:08:12.322478
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:after	2019-11-21 12:13:57.215433
@@ -1,5 +1,6 @@
+import six
+
 import re
-import six
 import warnings
 from string import Template

ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/api.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/api.py:before	2019-11-21 12:08:12.321477
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/api.py:after	2019-11-21 12:13:57.222470
@@ -1,11 +1,11 @@
+import six
+
 import base64
 import os
-import six
 from string import Template

 import requests
 from govdelivery import xml_payloads, xml_response_parsers
-

 if six.PY2:
     import urlparse  # pragma: no cover
ERROR: /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/utils.py Imports are incorrectly sorted.
--- /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/utils.py:before	2019-11-21 12:07:56.657335
+++ /Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/tests/utils.py:after	2019-11-21 12:13:57.234031
@@ -1,6 +1,5 @@
 import codecs
 from os import path
-

 testdata_dir = path.join(path.dirname(__file__), 'test_api_responses')

ERROR: InvocationError for command /Users/DaviesC/Projects/CFPB/govdelivery/.tox/lint/bin/isort --check-only --diff --recursive govdelivery (exited with code 1)
_____________________________________________________ summary ______________________________________________________
ERROR:   lint: commands failed```

**Comment by cwdavies** [comment]
```
$ tox -e py36
GLOB sdist-make: /Users/DaviesC/Projects/CFPB/govdelivery/setup.py
py36 inst-nodeps: /Users/DaviesC/Projects/CFPB/govdelivery/.tox/.tmp/package/1/govdelivery-1.2.zip
py36 installed: certifi==2019.9.11,chardet==3.0.4,coverage==4.5.4,govdelivery==1.2,idna==2.8,mock==2.0.0,pbr==5.4.3,requests==2.22.0,responses==0.10.6,six==1.13.0,urllib3==1.25.7
py36 run-test-pre: PYTHONHASHSEED='2808540161'
py36 run-test: commands[0] | coverage erase
py36 run-test: commands[1] | coverage run --source=govdelivery -m unittest discover
............./Users/DaviesC/Projects/CFPB/govdelivery/govdelivery/xml_payloads.py:15: DeprecationWarning: The phone number formatter will be deprecated in a future release of govdelivery. Going forward, please ensure that your application passes phone numbers in the format that the GovDelivery API requires (a ten-digit string with no punctuation).
  DeprecationWarning
..........
----------------------------------------------------------------------
Ran 23 tests in 0.012s

OK
py36 run-test: commands[2] | coverage report -m
Name                                             Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------
govdelivery/__init__.py                              1      0   100%
govdelivery/api.py                                  79     26    67%   58, 100-110, 130-137, 141-152, 168-179, 183-199, 207-228
govdelivery/tests/__init__.py                        0      0   100%
govdelivery/tests/test_api.py                       58      0   100%
govdelivery/tests/test_test_utils.py                 5      0   100%
govdelivery/tests/test_xml_payloads.py              39      0   100%
govdelivery/tests/test_xml_response_parsers.py      24      0   100%
govdelivery/tests/utils.py                           7      0   100%
govdelivery/xml_payloads.py                         47      6    87%   106-116, 120-129
govdelivery/xml_response_parsers.py                 31      0   100%
------------------------------------------------------------------------------
TOTAL                                              291     32    89%
_____________________________________________________ summary ______________________________________________________
  py36: commands succeeded
  congratulations :)```

**Comment by Scotchester** [comment]
@cwdavies Figured out the source of the problem. Please re-test once more. Thanks!

**Comment by cwdavies** [comment]
Works great and no issue with lint!
```
Name                                             Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------
govdelivery/__init__.py                              1      0   100%
govdelivery/api.py                                  79     26    67%   58, 100-110, 130-137, 141-152, 168-179, 183-199, 207-228
govdelivery/tests/__init__.py                        0      0   100%
govdelivery/tests/test_api.py                       58      0   100%
govdelivery/tests/test_test_utils.py                 5      0   100%
govdelivery/tests/test_xml_payloads.py              39      0   100%
govdelivery/tests/test_xml_response_parsers.py      24      0   100%
govdelivery/tests/utils.py                           7      0   100%
govdelivery/xml_payloads.py                         47      6    87%   107-117, 121-130
govdelivery/xml_response_parsers.py                 31      0   100%
------------------------------------------------------------------------------
TOTAL                                              291     32    89%
_____________________________________________________ summary ______________________________________________________
  lint: commands succeeded
  py27: commands succeeded
  py36: commands succeeded
  congratulations :)
```

**Pull request merged**
