### PR TITLE
Updated to match (emerging) CFPB PyPI guidance.

### PR DESCRIPTION
**Pull request by rosskarchner**
https://github.com/chosak/development/blob/e2a8eb7582eed6d104c24c4884f46bc8fd48024e/pypi.md

### CODE REVIEW

**Comment by rosskarchner** [comment]
I couldn't add @chosak as a reviewer, for some reason.

**Comment by chosak** [comment]
:+1: Thanks for doing this. That PR [has now been merged](https://github.com/cfpb/development/pull/151) -- one minor change is that we are recommending using the trove classifiers to specify the license instead of specifying [in setup.py](https://github.com/cfpb/govdelivery/pull/2/files#diff-2eeaed663bd0d25b7e608891384b7298R14) like you do here. It's a minor thing, besides that this is great!

**Comment by rosskarchner** [comment]
Thanks, will update

**Comment by rosskarchner** [comment]
@chosak I've made that change

**Review by chosak — APPROVED** [review]
Thanks, looks great!

**Pull request merged**
